// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6H_Jf8w8Z7wuybREYYDXklCOJWQk-aWM',
    appId: '1:893663631111:web:7b4278a3fc8238958397a2',
    messagingSenderId: '893663631111',
    projectId: 'fir-rank-54b7b',
    authDomain: 'fir-rank-54b7b.firebaseapp.com',
    storageBucket: 'fir-rank-54b7b.firebasestorage.app',
    measurementId: 'G-WY89SEMC9L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6fCiyjKSbFTVRxFvTO39DKB2NJilbu08',
    appId: '1:893663631111:android:bebb654e3999d0688397a2',
    messagingSenderId: '893663631111',
    projectId: 'fir-rank-54b7b',
    storageBucket: 'fir-rank-54b7b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6H_Jf8w8Z7wuybREYYDXklCOJWQk-aWM',
    appId: '1:893663631111:ios:bebb654e3999d0688397a2',
    messagingSenderId: '893663631111',
    projectId: 'fir-rank-54b7b',
    storageBucket: 'fir-rank-54b7b.firebasestorage.app',
    iosBundleId: 'com.example.srank',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6H_Jf8w8Z7wuybREYYDXklCOJWQk-aWM',
    appId: '1:893663631111:ios:bebb654e3999d0688397a2',
    messagingSenderId: '893663631111',
    projectId: 'fir-rank-54b7b',
    storageBucket: 'fir-rank-54b7b.firebasestorage.app',
    iosBundleId: 'com.example.srank',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6H_Jf8w8Z7wuybREYYDXklCOJWQk-aWM',
    appId: '1:893663631111:web:bebb654e3999d0688397a2',
    messagingSenderId: '893663631111',
    projectId: 'fir-rank-54b7b',
    authDomain: 'fir-rank-54b7b.firebaseapp.com',
    storageBucket: 'fir-rank-54b7b.firebasestorage.app',
  );
}
